sudo: required
services:
    - docker

script:
    docker build -t coanjos/roleta-russa-front .

after_success:    
    # Login
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Push to Docker Hub
    - docker push coanjos/roleta-russa-front

deploy:
    edge: true
    provider: elasticbeanstalk
    region: sa-east-1
    app: roleta-russa-front
    env: RoletaRussaFront-env
    bucket_name: elasticbeanstalk-sa-east-1-491740408545
    bucket_path: roleta-russa-front
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY